# https://taskfile.dev

version: '3'

vars: { }

tasks:
  run:
    desc: run the app. passes extra arguments
    cmd: go run main.go {{.CLI_ARGS}}

  debug:
    desc: run the app under dlv. passes extra arguments
    summary: |
      runs the app using dlv, allowing interactive debug. 
      dlv will listen on the provided dlv_port argument (default 4300)
    vars:
      dlv_port: '{{ .dlv_port | default 4300 }}'
    cmd: dlv debug --headless --listen=:{{.dlv_port}} --api-version=2 --accept-multiclient main.go -- {{.CLI_ARGS}}

  build:
    desc: builds the binary
    cmd: go build -o adr-er main.go

  pre-push:
    desc: test/cq before pushing
    cmds:
      - task: cq
      - task: test

  cq:
    desc: uber-common go cq commands
    cmds:
      - go mod tidy
      - task: vet

  lint:
    desc: runs the common case of golangci-lint
    cmd: golangci-lint run

  lint:single:
    desc: runs a single, specific linter
    summary: |
      runs golangci-lint with all disabled and config ignored, passing extra args to the --enable flag 
      usage ex, run only the lll linter:  
        $ task lint:single -- lll
      usage ex, run godo with fix mode: 
        $ task lint:single -- godot --fix
    cmd: golangci-lint run --no-config --disable-all --enable {{.CLI_ARGS}}

  vet:
    desc: run go vet
    cmd: go vet ./...

  test:
    desc: run unit tests
    cmd: go test ./...

  demo:
    desc: updates the gif demo(s)
    cmds:
      - task: build
      - vhs doc/demo/demo-create.tape