# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Release

on:
  workflow_dispatch: {} # allows manual runs
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      #
      # setup
      - uses: actions/checkout@v4
      - name: Setup Go # hint: setup-go automatically caches deps, keyed on go.sum
        uses: actions/setup-go@v5
        with: { go-version: '1.22.x' }

      #
      # go deps
      - name: Install dependencies
        run: go get

      #
      # build/test
      - name: Build
        run: go build -v -o adr-er main.go
      - name: Test
        run: go test -json ./... > TestResults.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults.json

  #
  # goreleaser
  goreleaser:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      #
      # setup
      - uses: actions/checkout@v4
        with:
          fetch-depth: '1'
          fetch-tags: 'true'

      - name: Setup Go
        uses: actions/setup-go@v5
        with: { go-version: '1.22.x' }

      #
      # go deps
      - name: Install dependencies
        run: go get

      #
      # release
      - name: Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}