# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      #
      # setup
      - uses: actions/checkout@v4

      # hint: setup-go automatically caches deps, keyed on go.sum
      - name: Setup Go
        uses: actions/setup-go@v5
        with: { go-version: '1.22.x' }

      #
      # go deps
      - name: Install dependencies
        run: go get

      #
      # build/test
      - name: Build
        run: go build -v -o adr-er main.go
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: adr-er binary
          path: adr-er

      - name: Test
        run: go test -json ./... > TestResults.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults.json
