# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lint and Test
permissions: { contents: read }

on:
  workflow_dispatch: { } # allows manual runs
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go # hint: setup-go automatically caches deps, keyed on go.sum
        uses: actions/setup-go@v5
        with: { go-version: '1.22.x' }
      - name: Install dependencies
        run: go get

      #
      # lint
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: '--max-issues-per-linter 0 --max-same-issues 0'


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go # hint: setup-go automatically caches deps, keyed on go.sum
        uses: actions/setup-go@v5
        with: { go-version: '1.22.x' }
      - name: Install dependencies
        run: go get

      #
      # test
      - name: Test
        run: go test -json ./...